export enum AuthErrorCode {
    DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
    ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
}
